---
name: CI (latest)

on:
  push:
    tags:
      - 'v*.*.*'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v2.1.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Compile
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Security tests
        run: |
          yarn run security:auth ${{ secrets.SNYK_API_TOKEN }}
          yarn run security:test
      - name: Unit tests
        run: yarn run test
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ['Performance']
      fail-fast: false
    steps:
      - uses: fabasoad/translation-action@main
        id: linguatools
        with:
          provider: linguatools
          lang: 'en-de'
          source: ${{ matrix.source }}
      - name: Validate Linguatools translation result
        run: |
          echo "'${{ matrix.source }}' has been translated to '${{ steps.linguatools.outputs.text }}'"
          [[ "${{ steps.linguatools.outputs.text }}" == "Leistung" ]] || exit 1;
        shell: bash
      - uses: fabasoad/translation-action@main
        id: mymemory_free
        with:
          provider: mymemory
          lang: 'en|pt'
          source: ${{ matrix.source }}
      - name: Validate MyMemory (Free) translation result
        run: |
          echo "'${{ matrix.source }}' has been translated to '${{ steps.mymemory_free.outputs.text }}'"
          [[ "${{ steps.mymemory_free.outputs.text }}" == "Live performance" ]] || exit 1;
        shell: bash
      - uses: fabasoad/translation-action@main
        id: mymemory_registered
        with:
          provider: mymemory
          api_key: ${{ secrets.MYMEMORY_API_KEY }}
          lang: 'en|it'
          source: ${{ matrix.source }}
      - name: Validate MyMemory (Registered) translation result
        run: |
          echo "'${{ matrix.source }}' has been translated to '${{ steps.mymemory_registered.outputs.text }}'"
          [[ "${{ steps.mymemory_registered.outputs.text }}" == "Elevate" ]] || exit 1;
        shell: bash
      - uses: fabasoad/translation-action@main
        id: funtranslations
        with:
          provider: funtranslations
          lang: 'klingon'
          source: ${{ matrix.source }}
      - name: Validate FunTranslations translation result
        run: |
          echo "'${{ matrix.source }}' has been translated to '${{ steps.funtranslations.outputs.text }}'"
          [[ "${{ steps.funtranslations.outputs.text }}" == "Performance" ]] || exit 1;
        shell: bash
